### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: missing revert data in call exception

### ISSUE THREAD

**Issue by donmega** [modagavr/pancakeswap-prediction-winner#35]
.

**Comment by svorwerk-dentsu** [comment]
I'm getting the same thing, I haven't been able to get this to work yet

**Comment by svorwerk-dentsu** [comment]
(node:892396) UnhandledPromiseRejectionWarning: Error: call revert exception (method="currentEpoch()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at Logger.makeError (/home/stephen/Downloads/test/pancakeswap-prediction-winner/pancakeswap-prediction-winner/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/stephen/Downloads/test/pancakeswap-prediction-winner/pancakeswap-prediction-winner/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Interface.decodeFunctionResult (/home/stephen/Downloads/test/pancakeswap-prediction-winner/pancakeswap-prediction-winner/node_modules/@ethersproject/abi/src.ts/interface.ts:425:23)
    at Contract.<anonymous> (/home/stephen/Downloads/test/pancakeswap-prediction-winner/pancakeswap-prediction-winner/node_modules/@ethersproject/contracts/src.ts/index.ts:392:44)
    at step (/home/stephen/Downloads/test/pancakeswap-prediction-winner/pancakeswap-prediction-winner/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/stephen/Downloads/test/pancakeswap-prediction-winner/pancakeswap-prediction-winner/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/stephen/Downloads/test/pancakeswap-prediction-winner/pancakeswap-prediction-winner/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by svorwerk-dentsu** [comment]
seems like it might have something to do with the provider address
